config/routes.rb
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

Shuttle::Application.routes.draw do
  # Redirect request with not matching hosts or protocol to a default url.
  # For example, `http://shuttle.server1.example.com` would redirect to `https://shuttle.example.com`
  # if the default url provided in the configs were `https://shuttle.example.com`.
  full_root_url = lambda { |opts| opts.fetch(:protocol, 'http') + '://' + opts.host + (opts.key?(:port) ? ':' + opts.port.to_s : '')}.call(Shuttle::Configuration.app.default_url_options)
  constraints(lambda { |req| !req.url.start_with?(full_root_url) }) do
    match '*glob' => redirect(full_root_url), via: [:get, :post, :put, :patch, :delete]
  end

  # AUTHENTICATION
  devise_for :users, controllers: {
      registrations: 'registrations'
  }

  # API
  namespace :api do
    namespace :v1 do
      resources :projects, only: [] do
        resources :articles, param: :name, only: [:index, :new, :create, :show, :edit, :update] do
          member do
            get :manifest, :issues
          end
        end
      end
    end
  end

  # IN-CONTEXT TRANSLATION
  constraints(key_id: /[^\s]+/) do
    get '/projects/:project_id/commits/:commit_id/keys/:key_id/translations/:id' => 'incontext/translations#show', as: :incontext_translation
    get '/projects/:project_id/commits/:commit_id/keys/:key_id/translations/:id/edit' => 'incontext/translations#edit', as: :edit_incontext_translation
  end

  # REST
  resources :projects do
    resources :commits, only: [:show, :create, :update, :destroy] do
      member do
        post :sync, :recalculate, :ping_stash
        get :manifest, :localize, :search, :tools, :gallery, :issues
      end

      resources :keys, only: [:index, :show], controller: 'commit/keys'
      resources :screenshots, only: [:create] do
        collection do
          post :request, to: :request_screenshots
        end
      end
    end

    resources :keys, only: [] do
      resources :translations, only: [:show, :new, :create, :edit, :update] do
        member do
          get :match, :fuzzy_match
        end
      end

      resources :translations, only: [] do
        resources :issues, only: [:create, :update] do
          member do
            patch :resolve
            patch :subscribe
            patch :unsubscribe
          end
        end
      end
    end

    member do
      post 'github-pull-request-builder' => 'projects#github_webhook'
      post 'stash-pull-request-builder' => 'projects#stash_webhook'
      get  'mass-copy-translations' => 'projects#setup_mass_copy_translations', as: :setup_mass_copy_translations
      post 'mass-copy-translations' => 'projects#mass_copy_translations', as: :mass_copy_translations
    end
  end

  resources :issues, only: [] do
    resources :comments, only: [:create]
  end

  resources :locales, only: :index do
    collection { get :countries }
    resources :projects, only: [:index, :show], controller: 'locale/projects' do
      resources :translations, controller: 'locale/translations', only: :index
    end
    resources :glossary_entries, only: [:index, :create, :update, :destroy]
  end

  resources :users, only: [:index, :show, :update, :destroy] do
    collection { get :search }
    member { post :become }
  end

  resources :locale_associations, except: :show

  get 'substitute' => 'substitution#convert'

  # SEARCH PAGES
  get 'search' => redirect('/search/translations')
  get 'search/translations' => 'search#translations', as: :search_translations
  get 'search/keys' => 'search#keys', as: :search_keys
  get 'search/commits' => 'search#commits', as: :search_commits

  # STATS PAGES
  get 'stats' => 'stats#index'

  # GLOSSARY PAGES
  get 'glossary' => 'glossary#index', as: :glossary
  namespace 'glossary' do
    resources :sources, only: [:index, :create, :edit, :update, :destroy], controller: 'source_glossary_entries' do
      resources :locales, only: [:create, :edit, :update], controller: 'locale_glossary_entries' do
        member { patch :approve, :reject }
      end
    end
  end

  # HOME PAGES
  get 'administrators' => 'home#administrators', as: :administrators
  get 'translators' => 'home#translators', as: :translators
  get 'reviewers' => 'home#reviewers', as: :reviewers
  root to: 'home#index'

  require 'sidekiq/web'
  begin
    require 'sidekiq/pro/web'
  rescue LoadError
    # no sidekiq pro
  end
  constraint = lambda { |request| request.env['warden'].authenticate? and request.env['warden'].user.admin? }
  constraints(constraint) { mount Sidekiq::Web => '/sidekiq' }

  get '/queue_status' => proc {
    queue_size   = %w(high low).map { |q| Sidekiq::Queue.new(q).size }.inject(:+)
    queue_status = if queue_size == 0
                     'idle'
                   elsif queue_size < 21
                     'working'
                   else
                     'heavy'
                   end
    [200, {'Content-Type' => 'text/plain'}, [queue_status]]
  }
end

app/controllers/incontext/translations_controller.rb
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

class Incontext::TranslationsController < ApplicationController
  before_filter :translator_required
  before_filter :allow_iframe_requests

  before_filter :find_project
  before_filter :find_commit
  before_filter :find_key
  before_filter :find_translation

  layout false
  respond_to :html

  def show
    if @translation.translated?
      render text: @translation.copy
    else
      render text: "<pending> #{@translation.source_copy}"
    end
  end

  def edit
    respond_with @translation, location: incontext_translation_url(@project, @commit, @key, @translation)
  end

  private
  def allow_iframe_requests
    response.headers.delete('X-Frame-Options')
  end

  def find_project
    @project = Project.find_from_slug!(params[:project_id])
  end

  def find_commit
    @commit = @project.commits.for_revision(params[:commit_id]).first!
  end

  def find_key
    @key = @commit.keys.for_key(params[:key_id]).first!
  end

  def find_translation
    @translation = @key.translations.where(rfc5646_locale: params[:id]).first!
  end
end

app/controllers/translations_controller.rb
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# Controller for working with Translations. The `TranslationWorkbench` JavaScript
# uses these endpoints to modify, approve, and reject Translations.

class TranslationsController < ApplicationController
  include TranslationDecoration

  before_filter :translator_required, only: [:edit, :update]

  before_filter :find_project
  before_filter :find_key
  before_filter :find_translation
  before_filter :find_issues, only: [:show, :edit]

  respond_to :html, except: [:match, :fuzzy_match]
  respond_to :json, only: [:show, :match, :fuzzy_match]

  # Displays a large-format translation view page.
  #
  # Routes
  # ------
  #
  # * `PATCH /projects/:project_id/keys/:key_id/translations/:id`
  #
  # Path Parameters
  # ---------------
  #
  # |              |                                    |
  # |:-------------|:-----------------------------------|
  # | `project_id` | The slug of a Project.             |
  # | `key_id`     | The slug of a Key in that project. |
  # | `id`         | The ID of a Translation.           |

  def show
    respond_with(@translation, location: project_key_translation_url(@project, @key, @translation)) do |format|
      format.json { render json: decorate([@translation]).first }
    end
  end

  # Displays a large-format translation edit page.
  #
  # Routes
  # ------
  #
  # * `PATCH /projects/:project_id/keys/:key_id/translations/:id/edit`
  #
  # Path Parameters
  # ---------------
  #
  # |              |                                    |
  # |:-------------|:-----------------------------------|
  # | `project_id` | The slug of a Project.             |
  # | `key_id`     | The slug of a Key in that project. |
  # | `id`         | The ID of a Translation.           |

  def edit
    respond_with @translation, location: project_key_translation_url(@project, @key, @translation)
  end

  # Updates a Translation with new translated copy. If the translated copy is
  # blank, the translation will be considered to have been "erased" (marked as
  # untranslated) unless the `blank_string` parameter is set.
  #
  # Routes
  # ------
  #
  # * `PATCH /projects/:project_id/keys/:key_id/translations/:id`
  #
  # Path Parameters
  # ---------------
  #
  # |              |                                    |
  # |:-------------|:-----------------------------------|
  # | `project_id` | The slug of a Project.             |
  # | `key_id`     | The slug of a Key in that project. |
  # | `id`         | The ID of a Translation.           |
  #
  # Body Parameters
  # ---------------
  #
  # |               |                                               |
  # |:--------------|:----------------------------------------------|
  # | `translation` | Parameterized hash of Translation attributes. |
  #
  # Query Parameters
  # ----------------
  #
  # |                |                                              |
  # |:---------------|:---------------------------------------------|
  # | `blank_string` | If true, a blank translated copy is allowed. |

  def update
    # translators cannot modify approved copy
    return head(:forbidden) if @translation.approved? && current_user.role == 'translator'

    mediator = TranslationUpdateMediator.new(@translation, current_user, params)
    mediator.update!

    respond_with(@translation, location: project_key_translation_url(@project, @key, @translation)) do |format|
      format.json do
        if mediator.success?
          render json: decorate([@translation]).first
        else
          render json: mediator.errors, status: :unprocessable_entity
        end
      end
      format.html do
        if mediator.success?
          redirect_to edit_project_key_translation_url(@project, @key, @translation), flash: { success: t('controllers.translations.update.success') }
        else
          redirect_to edit_project_key_translation_url(@project, @key, @translation), flash: { alert: mediator.errors.unshift(t('controllers.translations.update.failure')) }
        end
      end
    end
  end

  # Returns the first eligible Translation Unit that meets the following
  # requirements:
  #
  # * in the same locale,
  # * and has the same source copy.
  #
  # If multiple Translation Units match, priority is given to the most recently
  # updated Translation. If no Translation Units match in the same locale,
  # {Locale#fallbacks fallback} locales are tried in order. Under each
  # fallback locale, a Translation Unit is located that shares the same project, same
  # key, and same source copy. If no match is found, that same fallback locale
  # is searched for a Translation Unit with the same source copy, priority given to
  # the most recently modified Translation. If no match is found, the next more
  # general fallback locale is attempted.
  #
  # In all cases, the candidate Translation must be approved to match.
  #
  # Routes
  # ------
  #
  # * `GET /projects/:project_id/keys/:key_id/translations/:id/match`
  #
  # Path Parameters
  # ---------------
  #
  # |              |                                    |
  # |:-------------|:-----------------------------------|
  # | `project_id` | The slug of a Project.             |
  # | `key_id`     | The slug of a Key in that project. |
  # | `id`         | The ID of a Translation.           |
  #
  # Response
  # ========
  #
  # Returns 204 Not Content and an empty body if no match is found.

  def match
    source_copy = @translation.source_copy

    @translation.locale.fallbacks.each do |fallback|
      @match = Translation.search do
        filter :term, { approved: 1 }
        filter :term, { rfc5646_locale: fallback.rfc5646 }
        filter :term, { source_copy: source_copy }
        sort { by :created_at, 'desc' }
        size 1
      end.first

      break if @match
    end

    return head(:no_content) unless @match
    respond_with @match, location: project_key_translation_url(@project, @key, @translation)
  end

  #TODO return all matches, show popup

  # Returns up to 5 best fuzzy matching Translations that meets the following
  # requirements:
  #
  # * in the same locale,
  #
  # If multiple Translations match, priority is given to the most closely
  # matching Translations.
  #
  # Routes
  # ------
  #
  # * `GET /projects/:project_id/keys/:key_id/translations/:id/fuzzy_match`
  #
  # Path Parameters
  # ---------------
  #
  # |              |                                    |
  # |:-------------|:-----------------------------------|
  # | `project_id` | The slug of a Project.             |
  # | `key_id`     | The slug of a Key in that project. |
  # | `id`         | The ID of a Translation.           |
  #

  def fuzzy_match
    respond_to do |format|
      format.json do
        limit = 5
        query_filter = params[:source_copy] || @translation.source_copy
        target_locales = @translation.locale.fallbacks.map(&:rfc5646)
        @results = Translation.search(load: { include: { key: :project } }) do
          # TODO: Remove duplicate where source_copy, copy are same
          filter :term, { approved: 1 }
          filter :terms, { rfc5646_locale: target_locales }

          size limit
          query { match 'source_copy', query_filter, operator: 'or' }
        end
        render json: decorate_fuzzy_match(@results, query_filter).to_json
      end
    end
  end

  private

  def find_project
    @project = Project.find_from_slug!(params[:project_id])
  end

  def find_key
    @key = @project.keys.find_by_id!(params[:key_id])
  end

  def find_translation
    @translation = @key.translations.where(rfc5646_locale: params[:id]).first!
  end

  def find_issues
    @issues = @translation.issues.includes(:user, comments: :user).order_default
    @issue = Issue.new_with_defaults
  end

  def translation_params
    params.require(:translation).permit(:copy, :notes)
  end

  def decorate_fuzzy_match(translations, source_copy)
    translations = translations.map do |translation|
      {
          source_copy: translation.source_copy,
          copy: translation.copy,
          match_percentage: source_copy.similar(translation.source_copy),
          rfc5646_locale: translation.rfc5646_locale
      }
    end.reject { |t| t[:match_percentage] < 70 }
    translations.sort! { |a, b| b[:match_percentage] <=> a[:match_percentage] }
  end
end

app/views/translations/_article_details.slim
/ Copyright 2014 Square Inc.
/
/    Licensed under the Apache License, Version 2.0 (the "License");
/    you may not use this file except in compliance with the License.
/    You may obtain a copy of the License at
/
/        http://www.apache.org/licenses/LICENSE-2.0
/
/    Unless required by applicable law or agreed to in writing, software
/    distributed under the License is distributed on an "AS IS" BASIS,
/    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/    See the License for the specific language governing permissions and
/    limitations under the License.

/ Show the best guess as to who may have created this translation.
/ Requires the following local params:
/   - <Translation> translation

- article = translation.article

- if article
  fieldset
    legend Article Details

    dl
      .item
        dt Article
        dd = link_to(article.name, api_v1_project_article_path(article.project.id, article.name))
        dt Created At
        dd = l(article.created_at, format: :long)
      - if article.creator
        .item
          dt Creator
          dd = article.creator.name
          dt Creator Email
          dd = article.creator.email
      - if article.updater
        .item
          dt Updater
          dd = article.updater.name
          dt Updater Email
          dd = article.updater.email
      - if article.email.present?
        .item
          dt Contact Email
          dd = article.email

app/views/translations/_commit_history.slim
/ Copyright 2014 Square Inc.
/
/    Licensed under the Apache License, Version 2.0 (the "License");
/    you may not use this file except in compliance with the License.
/    You may obtain a copy of the License at
/
/        http://www.apache.org/licenses/LICENSE-2.0
/
/    Unless required by applicable law or agreed to in writing, software
/    distributed under the License is distributed on an "AS IS" BASIS,
/    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/    See the License for the specific language governing permissions and
/    limitations under the License.

/ Show the best guess as to who may have created this translation.
/ Requires the following local params:
/   - <Translation> translation

- commit = translation.potential_commit

- if commit
  fieldset
    legend Commit History

    p.help-block
      ' This is the first Commit in Shuttle with this Key. Remember that this data may not be accurate, i.e.
      ' the person below may not be the person who created this Key for several reasons such as
      ' some teams running scripts to create Keys (ex: iOS), not all SHAs being submitted to Shuttle,
      ' SHAs not being submitted in the order they were created in git repo, Shuttle deleting old SHAs.

    br

    dl
      .item
        dt SHA
        dd = link_to(commit.revision, commit.git_url)
        dt Created At
        dd = l(commit.created_at, format: :long)
      - if commit.user
        .item
          dt Submitter
          dd = commit.user.name
          dt Submitter Email
          dd = commit.user.email
      .item
        dt Author
        dd = commit.author
        dt Author Email
        dd = commit.author_email

app/views/translations/_details.slim
/ Copyright 2014 Square Inc.
/
/    Licensed under the Apache License, Version 2.0 (the "License");
/    you may not use this file except in compliance with the License.
/    You may obtain a copy of the License at
/
/        http://www.apache.org/licenses/LICENSE-2.0
/
/    Unless required by applicable law or agreed to in writing, software
/    distributed under the License is distributed on an "AS IS" BASIS,
/    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/    See the License for the specific language governing permissions and
/    limitations under the License.

/ Requires the following local params:
/   - <Translation> translation

fieldset.details
  legend Details

  dl
    .item
      dt String ID
      dd = translation.key.id
    .item
      dt Key
      dd = translation.key.original_key
    .item
      dt Context
      dd = (translation.key.context || "none")
    - if translation.key.importer
      .item
        dt Importer
        dd = translation.key.importer_name
    - if translation.key.fencers.present?
      .item
        dt Fencers
        dd = translation.key.fencers.map { |f| I18n.t("fencer.#{f}") }.to_sentence
    - if translation.key.source.present?
      .item
        dt Source
        dd = translation.key.source
    - if translation.translator
      .item
        dt Translator
        dd = translation.translator.name
    - if translation.reviewer
      .item
        dt Reviewer
        dd = translation.reviewer.name
    .item class=(if translation.approved == false then "text-error" elsif @translation.approved == true then "text-success" end)
      dt Status
      dd
        - if translation.approved.nil?
          = translation.translated? ? "Pending Approval" : "Pending Translation"
        - elsif translation.approved == false
          | Rejected
        - elsif translation.approved == true
          | Approved

app/views/translations/_translation_history.slim
/ Copyright 2014 Square Inc.
/
/    Licensed under the Apache License, Version 2.0 (the "License");
/    you may not use this file except in compliance with the License.
/    You may obtain a copy of the License at
/
/        http://www.apache.org/licenses/LICENSE-2.0
/
/    Unless required by applicable law or agreed to in writing, software
/    distributed under the License is distributed on an "AS IS" BASIS,
/    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/    See the License for the specific language governing permissions and
/    limitations under the License.

/ Requires the following local params:
/   - <Translation> translation

- if translation.translation_changes.present?
  fieldset
    legend Translation History

    .translation-history
      - translation.translation_changes.reverse.each do |change|
        .history-entry
          strong = change.user.present? ? change.user.name : "(Automatic)"
          .pull-right: strong = l(change.created_at, format: :long)

          - if change.diff["approved"].present?
            .change
              - if change.diff["copy"].present?
                .change-state class=TranslationChange.style(change.diff["approved"][0])
                  = change.transition_from
                .arrow
                .change-state class=TranslationChange.style(change.diff["approved"][1])
                  = change.transition_to

          .change.copy
            - if change.diff["copy"].present?
              .change-state[
                data-full=(change.full_copy_from ? change.full_copy_from : "None")
                data-compact=(change.compact_copy_from ? change.compact_copy_from : "None")
                ]
                = change.compact_copy_from ? change.compact_copy_from : "None"
              .arrow
                i.fa.fa-double-angle-right.text-error
              .change-state[
                data-full=(change.full_copy_to ? change.full_copy_to : "None")
                data-compact=(change.compact_copy_to ? change.compact_copy_to : "None")
                ]
                = change.compact_copy_to ? change.compact_copy_to : "None"

app/views/translations/edit.js.coffee.erb
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

$(document).ready ->
  find_fuzzy_matches = (source_copy, locale) ->
    loadFuzzyMatches($('.fuzzy-matches').first(),
                     copy_field,
                     "<%= fuzzy_match_project_key_translation_url(@translation.key.project, @translation.key, @translation, format: 'json') %>",
                     source_copy)

  source_copy = "<%= escape_javascript @translation.source_copy %>"
  target_locale = "<%= escape_javascript @translation.rfc5646_locale %>"

  current_selection = source_copy

  blankString = $("input[name=blank_string]")
  copy_field = $("#translation_copy")
  source_copy_field = $("#source_copy")

  blankString.checked = true  if copy_field.val().match(/^\s*$/)
  blankString.change ->
    $("#translation_copy").val ""  if blankString[0].checked

  copy_field.keyup ->
    blankString[0].checked = copy_field.val().match(/^\s*$/)
    true
  $(".copy-source").click ->
    copy_field.val "<%= escape_javascript @translation.source_copy %>"
    false

  source_copy_field.click ->
    selection_string = window.getSelection().toString()

    if selection_string.length > 0 and selection_string != current_selection
      current_selection = selection_string
      source_copy_field.removeHighlight()
      source_copy_field.highlight(current_selection)
      find_fuzzy_matches(current_selection, target_locale)

  $(".history-entry").click (e) ->
    $.each( $(this).find(".change.copy > .change-state"), (i, elt) ->
      if $(this).hasClass("full")
        $(this).fadeOut( () ->
          $(this).text( $(this).data("compact"))
                 .removeClass("full")
                 .fadeIn()
        )
      else
        $(this).fadeOut( () ->
          $(this).text( $(this).data("full") )
                 .addClass("full")
                 .fadeIn()
        )
    )

  find_fuzzy_matches(source_copy, target_locale)

app/views/translations/edit.slim
/ Copyright 2014 Square Inc.
/
/    Licensed under the Apache License, Version 2.0 (the "License");
/    you may not use this file except in compliance with the License.
/    You may obtain a copy of the License at
/
/        http://www.apache.org/licenses/LICENSE-2.0
/
/    Unless required by applicable law or agreed to in writing, software
/    distributed under the License is distributed on an "AS IS" BASIS,
/    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/    See the License for the specific language governing permissions and
/    limitations under the License.
- content_for :shuttle_title do
  = "Translation #{@translation.id} - Shuttle"
- content_for :file_name do
  = 'views/translations/edit'

/ Status Line
.header
  h1
    | #{@translation.key.project.name}
    strong &nbsp;>&nbsp;
    | Translation #{@translation.id}
  = render partial: 'issues/notifications_on_translation_page_header', locals: { issues: @issues }


hr.divider

/ Filter Bar
= form_for @translation, url: project_key_translation_url(@project, @key, @translation), html: {id: 'large-translation'} do |f|
  .entry.row
    / Edit Side
    .eight.columns.edit-side
      fieldset
        legend = @translation.locale.name

        .control-group
          = f.text_area :copy, autocomplete: 'off', rows: 15, class: 'resize'

        .control-group
          = check_box_tag 'blank_string', '1', (@translation.translated? && @translation.copy.blank? ? 'checked' : nil)
          | The translation is a blank string

        .control-group
          .fuzzy-matches

      fieldset
        legend Notes

        .control-group
          = f.text_area :notes, autocomplete: 'off', rows: 7, class: 'resize'

      .form-actions
        = f.submit class: 'primary', value: 'Save'
            
        

    / Information Side
    .eight.columns.info-side
      button.small.default.copy-source Copy to #{@translation.locale.name}
      fieldset 
        legend = @translation.source_locale.name

        .control-group
          #source_copy.well.seven.columns
            span.highlight
              = @translation.source_copy

      = render partial: 'details', locals: { translation: @translation }
      = render partial: 'translation_history', locals: { translation: @translation }
      = render partial: (@translation.belongs_to_article? ? 'article_details' : 'commit_history'), locals: { translation: @translation }

= render partial: 'issues/index', locals: {project: @project, key: @key, translation: @translation, issues: @issues, issue: @issue}

app/views/translations/show.slim
/ Copyright 2014 Square Inc.
/
/    Licensed under the Apache License, Version 2.0 (the "License");
/    you may not use this file except in compliance with the License.
/    You may obtain a copy of the License at
/
/        http://www.apache.org/licenses/LICENSE-2.0
/
/    Unless required by applicable law or agreed to in writing, software
/    distributed under the License is distributed on an "AS IS" BASIS,
/    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/    See the License for the specific language governing permissions and
/    limitations under the License.

- content_for :shuttle_title do
  = "Translation #{@translation.source_copy} - Shuttle"
- content_for :file_name do
  = 'views/translations/show'

/ Status Line
.header
  h1
    | #{@translation.key.project.name}
    strong &nbsp;>&nbsp;
    | Translation #{@translation.id}
  = render partial: 'issues/notifications_on_translation_page_header', locals: { issues: @issues }


hr.divider

/ Filter Bar
.entry.row
  / Edit Side
  .eight.columns.edit-side
    fieldset 
      legend = @translation.locale.name

      .control-group
        label.control-label = @translation.locale.name
        .controls
          textarea.resize readonly="readonly" rows=7
            = @translation.copy
          - if current_user.translator?
            = link_to edit_project_key_translation_path(@project, @key, @translation), class: "edit-page-link button default square" do
              i.fa.fa-pencil-square-o

  / Information Side
  .eight.columns.info-side
    fieldset 
      legend = @translation.source_locale.name

      .control-group
        label.control-label English
        .controls 
          textarea.resize readonly="readonly" rows=7 
            = @translation.source_copy

    = render partial: 'details', locals: { translation: @translation }
    = render partial: 'translation_history', locals: { translation: @translation }
    = render partial: (@translation.belongs_to_article? ? 'article_details' : 'commit_history'), locals: { translation: @translation }

= render partial: 'issues/index', locals: {project: @project, key: @key, translation: @translation, issues: @issues, issue: @issue}