config/routes.rb
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

Shuttle::Application.routes.draw do
  # Redirect request with not matching hosts or protocol to a default url.
  # For example, `http://shuttle.server1.example.com` would redirect to `https://shuttle.example.com`
  # if the default url provided in the configs were `https://shuttle.example.com`.
  full_root_url = lambda { |opts| opts.fetch(:protocol, 'http') + '://' + opts.host + (opts.key?(:port) ? ':' + opts.port.to_s : '')}.call(Shuttle::Configuration.app.default_url_options)
  constraints(lambda { |req| !req.url.start_with?(full_root_url) }) do
    match '*glob' => redirect(full_root_url), via: [:get, :post, :put, :patch, :delete]
  end

  # AUTHENTICATION
  devise_for :users, controllers: {
      registrations: 'registrations'
  }

  # API
  namespace :api do
    namespace :v1 do
      resources :projects, only: [] do
        resources :articles, param: :name, only: [:index, :new, :create, :show, :edit, :update] do
          member do
            get :manifest, :issues
          end
        end
      end
    end
  end

  # IN-CONTEXT TRANSLATION
  constraints(key_id: /[^\s]+/) do
    get '/projects/:project_id/commits/:commit_id/keys/:key_id/translations/:id' => 'incontext/translations#show', as: :incontext_translation
    get '/projects/:project_id/commits/:commit_id/keys/:key_id/translations/:id/edit' => 'incontext/translations#edit', as: :edit_incontext_translation
  end

  # REST
  resources :projects do
    resources :commits, only: [:show, :create, :update, :destroy] do
      member do
        post :sync, :recalculate, :ping_stash
        get :manifest, :localize, :search, :tools, :gallery, :issues
      end

      resources :keys, only: [:index, :show], controller: 'commit/keys'
      resources :screenshots, only: [:create] do
        collection do
          post :request, to: :request_screenshots
        end
      end
    end

    resources :keys, only: [] do
      resources :translations, only: [:show, :new, :create, :edit, :update] do
        member do
          get :match, :fuzzy_match
        end
      end

      resources :translations, only: [] do
        resources :issues, only: [:create, :update] do
          member do
            patch :resolve
            patch :subscribe
            patch :unsubscribe
          end
        end
      end
    end

    member do
      post 'github-pull-request-builder' => 'projects#github_webhook'
      post 'stash-pull-request-builder' => 'projects#stash_webhook'
      get  'mass-copy-translations' => 'projects#setup_mass_copy_translations', as: :setup_mass_copy_translations
      post 'mass-copy-translations' => 'projects#mass_copy_translations', as: :mass_copy_translations
    end
  end

  resources :issues, only: [] do
    resources :comments, only: [:create]
  end

  resources :locales, only: :index do
    collection { get :countries }
    resources :projects, only: [:index, :show], controller: 'locale/projects' do
      resources :translations, controller: 'locale/translations', only: :index
    end
    resources :glossary_entries, only: [:index, :create, :update, :destroy]
  end

  resources :users, only: [:index, :show, :update, :destroy] do
    collection { get :search }
    member { post :become }
  end

  resources :locale_associations, except: :show

  get 'substitute' => 'substitution#convert'

  # SEARCH PAGES
  get 'search' => redirect('/search/translations')
  get 'search/translations' => 'search#translations', as: :search_translations
  get 'search/keys' => 'search#keys', as: :search_keys
  get 'search/commits' => 'search#commits', as: :search_commits

  # STATS PAGES
  get 'stats' => 'stats#index'

  # GLOSSARY PAGES
  get 'glossary' => 'glossary#index', as: :glossary
  namespace 'glossary' do
    resources :sources, only: [:index, :create, :edit, :update, :destroy], controller: 'source_glossary_entries' do
      resources :locales, only: [:create, :edit, :update], controller: 'locale_glossary_entries' do
        member { patch :approve, :reject }
      end
    end
  end

  # HOME PAGES
  get 'administrators' => 'home#administrators', as: :administrators
  get 'translators' => 'home#translators', as: :translators
  get 'reviewers' => 'home#reviewers', as: :reviewers
  root to: 'home#index'

  require 'sidekiq/web'
  begin
    require 'sidekiq/pro/web'
  rescue LoadError
    # no sidekiq pro
  end
  constraint = lambda { |request| request.env['warden'].authenticate? and request.env['warden'].user.admin? }
  constraints(constraint) { mount Sidekiq::Web => '/sidekiq' }

  get '/queue_status' => proc {
    queue_size   = %w(high low).map { |q| Sidekiq::Queue.new(q).size }.inject(:+)
    queue_status = if queue_size == 0
                     'idle'
                   elsif queue_size < 21
                     'working'
                   else
                     'heavy'
                   end
    [200, {'Content-Type' => 'text/plain'}, [queue_status]]
  }
end

app/controllers/search_controller.rb
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

class SearchController < ApplicationController
  # The number of records to return by default.
  PER_PAGE = 50

  def translations
    @presenter = TranslationsSearchPresenter.new(current_user.translator?)
    form  = SearchTranslationsForm.new(params)
    if form[:target_locales].present?
      return head(:unprocessable_entity) unless form[:target_locales].all?
    end
    translations_finder = SearchTranslationsFinder.new(form)
    @results = translations_finder.find_translations
  end



  def keys
    respond_to do |format|
      format.html # keys.html.erb
      format.json do
        return head(:unprocessable_entity) if params[:project_id].to_i <= 0

        if params[:metadata] # return metadata about the search only
          @project = Project.find(params[:project_id])
          render json: {
                           locales: ([@project.base_locale] + @project.targeted_locales.sort_by(&:rfc5646)).uniq
                       }.to_json
        else
          query_filter = params[:filter]
          status       = params[:status]
          offset       = params[:offset].to_i
          id           = params[:project_id]
          limit        = params.fetch(:limit, PER_PAGE)
          not_elastic  = params[:not_elastic_search] 

          @results = Key.search(load: {include: [:translations, :project]}) do
            if query_filter.present?
              if not_elastic
                filter :term, original_key_exact: query_filter
              else
                query { match 'original_key', query_filter, operator: 'and' }
              end
            else
              sort { by :original_key, 'asc' }
            end
            filter :term, project_id: id

            unless status.blank?
              filter :term, ready: status
            end

            from offset
            size limit
          end
          render json: decorate_keys(@results).to_json
        end
      end
    end
  end

  def commits
    respond_to do |format|
      format.html
      format.json do
        return head(:unprocessable_entity) if params[:project_id].to_i < 0

        sha = params[:sha]
        project_id = params[:project_id].to_i
        limit = params.fetch(:limit, 50)

        @results = Commit.search(load: {include: :project}) do
          filter :prefix, revision: sha if sha
          filter :term, project_id: project_id if project_id > 0
          size limit
          sort { by :created_at, 'desc' }
        end

        render json: decorate_commits(@results).to_json
      end
    end
  end

  private

  def decorate_translations(translations)
    translations.map do |translation|
      translation.as_json.merge(
          locale:        translation.locale.as_json,
          source_locale: translation.source_locale.as_json,
          url:           (
                         if current_user.translator?
                           edit_project_key_translation_url(translation.key.project, translation.key, translation)
                         else
                           project_key_translation_url(translation.key.project, translation.key, translation)
                         end),
          project:       translation.key.project.as_json,
          key:           translation.key.key
      )
    end
  end

  def decorate_keys(keys)
    keys.map do |key|
      translations = if current_user.approved_locales.empty? then
                       key.translations
                     else
                       key.translations.select { |t| current_user.approved_locales.include?(t.locale) }
                     end
      key.as_json.merge(
          translations: translations.map do |translation|
            translation.as_json.merge(
                url: if current_user.translator?
                       edit_project_key_translation_url(translation.key.project, translation.key, translation)
                     else
                       project_key_translation_url(translation.key.project, translation.key, translation)
                     end
            )
          end
      )
    end
  end

  def decorate_commits(commits)
    commits.map do |commit|
      commit.as_json.merge(
          url:     project_commit_url(commit.project, commit),
          project: commit.project
      )
    end
  end
end

app/views/search/commits.js.coffee.erb
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

$(window).ready ->
  firstTime = true

  formatTable = (commitTable) ->
    commitTable.empty()
    thead = $('<thead/>').appendTo(commitTable)
    header = $('<tr/>').appendTo(thead)
    $('<th/>').text('SHA').appendTo(header)
    $('<th/>').text('Project').appendTo(header)
    $('<th/>').text('Status').appendTo(header)


  addCommit = (commitTable, commit) ->
    tr = $('<tr/>').appendTo(commitTable)

    $('<a>', {
      text: commit.revision
      href: commit.url
    }).appendTo( $('<td/>').appendTo tr )
    $('<td/>').text(commit.project.name).appendTo(tr)

    klass = ''
    status = ''
    if commit.ready
      status = 'Ready'
      klass = 'text-success'
    else if commit.loading
      status = 'Loading'
      klass = 'text-info'
    else # In progress
      status = 'In Progress'
      klass = ''
    $('<td/>').text(status).addClass(klass).appendTo(tr)

  commitSearchForm = $('#commit-search-form')
  commitTable = $('#commits')
  prefillForm = ->
    commitSearchForm.find('[name]')
      .not('meta')
      .not('[type=hidden]')
      .not('[type=submit]').each (i, elt) ->
        prefillVal = $.url().param( $(elt).attr('name') )
        if $(elt).is('select') and !prefillVal
          $(elt).prop('selectedIndex', 0)
        else
          $(elt).val(prefillVal)
  prefillForm()

  formatTable(commitTable)
  makeCommitURL = -> "#{commitTable.data('url')}?#{commitSearchForm.serialize()}"
  
  commitScroll = commitTable.infiniteScroll makeCommitURL,
    windowScroll: true
    renderer: (commits) ->
      for commit in commits
        do (commit) -> addCommit(commitTable, commit)
    dataSourceOptions: {type: 'GET'}

  submitSearch = ->
    $.ajax commitTable.data('url'),
      data: commitSearchForm.serialize()
      success: (commits) ->
        commitScroll.reset()
        formatTable(commitTable)
        commitScroll.loadNextPage()
      error: =>
        new Flash('alert').text("Couldn't load search results");

  commitSearchForm.submit ->
    window.history.pushState("params", "", "?#{commitSearchForm.serialize()}")
    submitSearch()
    false

  window.onpopstate = ->
    unless firstTime
      prefillForm()
      submitSearch()
    firstTime = false

app/views/search/commits.slim
/ Copyright 2014 Square Inc.
/
/    Licensed under the Apache License, Version 2.0 (the "License");
/    you may not use this file except in compliance with the License.
/    You may obtain a copy of the License at
/
/        http://www.apache.org/licenses/LICENSE-2.0
/
/    Unless required by applicable law or agreed to in writing, software
/    distributed under the License is distributed on an "AS IS" BASIS,
/    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/    See the License for the specific language governing permissions and
/    limitations under the License.
- content_for :shuttle_title do
  = "Commits Search - Shuttle"
- content_for :file_name do
  = 'views/search/commits'

.header
  h1 Commits Search

hr.divider

/ tab-content
.border
  .filter-bar
    = form_tag(search_commits_url(format: 'json'), method: :get, id: 'commit-search-form', class: 'filter form-inline') do
      .main
        .pull-right.expand-search
          i.fa.fa-chevron-right
        = text_field_tag 'sha', '', placeholder: '935ad4', id: 'commit-sha-field'
        = submit_tag 'Search', class: 'primary'

      .collapse 

        .control-group 
          = label_tag 'project_id', 'Projects', class: 'control-label'
          .controls
            - project_list = Project.order('LOWER(name) ASC').map { |pr| [pr.name, pr.id] }
            - project_list.unshift ['all', nil]
            = select_tag 'project_id', options_for_select(project_list)
  
  table.table#commits data-url=search_commits_url(format: 'json')

app/views/search/keys.js.coffee.erb
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

$(window).ready ->
  # Methods
  localeOrder = []

  formatTable = (keyTable, locales) ->
    keyTable.empty()
    thead = $('<thead/>').appendTo(keyTable)
    header = $('<tr/>').appendTo(thead)
    $('<th/>').text("String ID").appendTo header
    $('<th/>').text("Key").appendTo header

    if locales
      for locale in locales
        do (locale) ->
          $('<th/>').text(locale.rfc5646).appendTo header

  addKey = (keyTable, key) ->
    tr = $('<tr/>').appendTo(keyTable)
    idTD = $('<td/>').text(key.id).appendTo(tr)
    keyTD = $('<td/>').text(key.original_key).appendTo(tr)
    $('<br/>').appendTo(keyTD)
    $('<small/>').addClass('muted').text(key.source).appendTo(keyTD)
    for locale in localeOrder
      do (locale) ->
        translation = (trans for trans in key.translations when trans.locale.rfc5646 == locale)[0]
        if translation?
          klass = if translation.translated && translation.approved
            'text-success'
          else if translation.translated
            'text-info'
          else if translation.approved == false
            'text-error'
          else
            'muted'

          copy = if translation.translated == false
            "(not yet translated)"
          else if /\A\s*\z/.test(translation.copy)
            "(blank string)"
          else
            translation.copy[0..30]

          td = $('<td/>').appendTo(tr)
          $('<a/>').attr('href', translation.url).addClass(klass).text(copy).appendTo(td)
        else
          td = $('<td/>').appendTo(tr)

  # Window on-ready
  keyTable = $('#keys')
  keySearchForm = $('#key-search-form')
  prefillForm = ->
    keySearchForm.find('[name]')
    .not('meta')
    .not('[type=hidden]')
    .not('[type=submit]').each (i, elt) ->
      prefillVal = $.url().param( $(elt).attr('name') )
      if $(elt).is('select') and !prefillVal
        $(elt).prop('selectedIndex', 0)
      else
        $(elt).val(prefillVal)
  prefillForm()

  makeKeyURL = -> "#{keyTable.data('url')}?#{keySearchForm.serialize()}"

  keyScroll = keyTable.infiniteScroll makeKeyURL,
    windowScroll: true
    renderer: (keys) =>
      for key in keys
        do (key) -> addKey(keyTable, key)

  submitSearch = ->
    $.ajax keyTable.data('url'),
      data: keySearchForm.serialize() + '&metadata=true'
      success: (metadata) ->
        keyScroll.reset()
        # record the order of locales for consistency
        localeOrder = (locale.rfc5646 for locale in metadata.locales)
        formatTable(keyTable, metadata.locales)
        keyScroll.loadNextPage()

      error: ->
        new Flash('alert').text("Couldn't load search results")

  keySearchForm.submit ->
    window.history.pushState("params", "", "?#{keySearchForm.serialize()}")
    submitSearch()
    false

  window.onpopstate = ->
    prefillForm()
    submitSearch()

app/views/search/keys.slim
/ Copyright 2014 Square Inc.
/
/    Licensed under the Apache License, Version 2.0 (the "License");
/    you may not use this file except in compliance with the License.
/    You may obtain a copy of the License at
/
/        http://www.apache.org/licenses/LICENSE-2.0
/
/    Unless required by applicable law or agreed to in writing, software
/    distributed under the License is distributed on an "AS IS" BASIS,
/    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/    See the License for the specific language governing permissions and
/    limitations under the License.
- content_for :shuttle_title do
  = "Keys Search - Shuttle"
- content_for :file_name do
  = 'views/search/keys'

.header
  h1 Keys Search

hr.divider

.border 
  .filter-bar 
    = form_tag(search_keys_url(format: 'json'), method: :get, id: 'key-search-form', class: 'filter form-inline') do
      .main
        .pull-right.expand-search
          i.fa.fa-chevron-right
        = text_field_tag 'filter', '', placeholder: 'Filter by Key', id: 'key-filter-field'    
        - project_list = Project.order('LOWER(name) ASC').map { |pr| [pr.name, pr.id] }
        = select_tag 'project_id', options_for_select(project_list)
        = submit_tag 'Search', class: 'primary'

      .collapse 
        .control-group 
          = label_tag 'status', 'Key Status', class: 'control-label'
          .controls
            = select_tag 'status', options_for_select(\
                      [\
                        ['all', nil],\
                        ['ready', true],\
                        ['not ready', false]\
                      ]\
                    ), id: 'key-status-select'
          .controls
            = check_box_tag 'not_elastic_search', true
            | Search for exact matches

  table.table#keys data-url=search_keys_url(format: 'json')

app/views/search/translations.js.coffee.erb
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

$(window).ready ->
  $(".datepicker").datepicker(autoclose: true)

  translationSearchForm = $('#translation-search-form')
  prefillForm = ->
    translationSearchForm.find('[name]')
      .not('meta')
      .not('[type=hidden]')
      .not('[type=submit]').each (i, elt) ->
        prefillVal = $.url().param( $(elt).attr('name') )
        if $(elt).is('select') and !prefillVal
          $(elt).prop('selectedIndex', 0)
        else
          $(elt).val(prefillVal)

  prefillForm()

#  TODO: Use Select2 instead

  $('select[name="translator_id"]').chosen
    width: "100%"

app/views/search/translations.slim
/ Copyright 2014 Square Inc.
/
/    Licensed under the Apache License, Version 2.0 (the "License");
/    you may not use this file except in compliance with the License.
/    You may obtain a copy of the License at
/
/        http://www.apache.org/licenses/LICENSE-2.0
/
/    Unless required by applicable law or agreed to in writing, software
/    distributed under the License is distributed on an "AS IS" BASIS,
/    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/    See the License for the specific language governing permissions and
/    limitations under the License.
- content_for :shuttle_title do
  = "Translations Search - Shuttle"
- content_for :file_name do
  = 'views/search/translations'

.header
  h1 Translation Search

hr.divider
div
  .filter-bar
    / translation_search_bar
    = form_tag(search_translations_url, method: 'GET', id: 'translation-search-form', class: 'filter form-inline')
      .main
        .pull-right.expand-search
          i.fa.fa-chevron-right
        = text_field_tag 'query', '', id: 'search-field', placeholder: 'Translation Query'
        - project_list = Project.order('LOWER(name) ASC').map { |pr| [pr.name, pr.id] }
        - project_list.unshift ['all projects', nil]
        = select_tag 'project_id', options_for_select(project_list)
        = select_tag 'field', options_for_select([\
                                                     %w(source searchable_source_copy),\
                                                     %w(translation searchable_copy),\
                                                 ]), id: 'field-select', class: 'span2'
        = submit_tag 'Search', class: 'primary'

      .collapse
        .control-group
          = label_tag 'target_locales', 'Target Locales', class: 'control-label'
          .controls
            - if current_user.approved_locales.any?
              = select_tag 'target_locales', options_for_select(current_user.approved_locales.map { |l| [l.name, l.rfc5646] })
            - else
              = text_field_tag 'target_locales', '', class: 'locale-field', id: '', placeholder: 'any target locale'

        .control-group
          = label_tag 'translator_id', 'Translator', class: 'control-label'
          .controls
            = select_tag 'translator_id', options_for_select(User.order('email ASC').map { |u| [u.name, u.id] }.unshift(['Anyone', nil]))

        .control-group
          = label_tag 'start_date', 'Start Date', class: 'control-label'
          .controls
            = text_field_tag 'start_date', '', class: 'datepicker'

        .control-group
          = label_tag 'end_date', 'End Date', class: 'control-label'
          .controls
            = text_field_tag 'end_date', '', class: 'datepicker'

  .pagination-links
    = paginate @results

  / translation_grid
  table.border.table#translations data-url=search_translations_url(format: 'json')
    thead
      tr
        th Project
        th ID
        th From
        th Source
        th To
        th Translation
        th Key
    tbody
      - @results.each do |translation|
        tr
          td = @presenter.project(translation)
          td
            a href=@presenter.url(translation) = @presenter.url_text(translation)
          td = @presenter.from(translation)
          td = @presenter.source(translation)
          td = @presenter.to(translation)
          td.translation-entry[class=@presenter.translation_class_name(translation)] = @presenter.translation_text(translation)
          td.key = @presenter.key(translation)
.row
  .pagination-links
    = paginate @results
.row
  .pagination-info
    = page_entries_info(@results, entry_name: 'translations')