config/routes.rb
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

Shuttle::Application.routes.draw do
  # Redirect request with not matching hosts or protocol to a default url.
  # For example, `http://shuttle.server1.example.com` would redirect to `https://shuttle.example.com`
  # if the default url provided in the configs were `https://shuttle.example.com`.
  full_root_url = lambda { |opts| opts.fetch(:protocol, 'http') + '://' + opts.host + (opts.key?(:port) ? ':' + opts.port.to_s : '')}.call(Shuttle::Configuration.app.default_url_options)
  constraints(lambda { |req| !req.url.start_with?(full_root_url) }) do
    match '*glob' => redirect(full_root_url), via: [:get, :post, :put, :patch, :delete]
  end

  # AUTHENTICATION
  devise_for :users, controllers: {
      registrations: 'registrations'
  }

  # API
  namespace :api do
    namespace :v1 do
      resources :projects, only: [] do
        resources :articles, param: :name, only: [:index, :new, :create, :show, :edit, :update] do
          member do
            get :manifest, :issues
          end
        end
      end
    end
  end

  # IN-CONTEXT TRANSLATION
  constraints(key_id: /[^\s]+/) do
    get '/projects/:project_id/commits/:commit_id/keys/:key_id/translations/:id' => 'incontext/translations#show', as: :incontext_translation
    get '/projects/:project_id/commits/:commit_id/keys/:key_id/translations/:id/edit' => 'incontext/translations#edit', as: :edit_incontext_translation
  end

  # REST
  resources :projects do
    resources :commits, only: [:show, :create, :update, :destroy] do
      member do
        post :sync, :recalculate, :ping_stash
        get :manifest, :localize, :search, :tools, :gallery, :issues
      end

      resources :keys, only: [:index, :show], controller: 'commit/keys'
      resources :screenshots, only: [:create] do
        collection do
          post :request, to: :request_screenshots
        end
      end
    end

    resources :keys, only: [] do
      resources :translations, only: [:show, :new, :create, :edit, :update] do
        member do
          get :match, :fuzzy_match
        end
      end

      resources :translations, only: [] do
        resources :issues, only: [:create, :update] do
          member do
            patch :resolve
            patch :subscribe
            patch :unsubscribe
          end
        end
      end
    end

    member do
      post 'github-pull-request-builder' => 'projects#github_webhook'
      post 'stash-pull-request-builder' => 'projects#stash_webhook'
      get  'mass-copy-translations' => 'projects#setup_mass_copy_translations', as: :setup_mass_copy_translations
      post 'mass-copy-translations' => 'projects#mass_copy_translations', as: :mass_copy_translations
    end
  end

  resources :issues, only: [] do
    resources :comments, only: [:create]
  end

  resources :locales, only: :index do
    collection { get :countries }
    resources :projects, only: [:index, :show], controller: 'locale/projects' do
      resources :translations, controller: 'locale/translations', only: :index
    end
    resources :glossary_entries, only: [:index, :create, :update, :destroy]
  end

  resources :users, only: [:index, :show, :update, :destroy] do
    collection { get :search }
    member { post :become }
  end

  resources :locale_associations, except: :show

  get 'substitute' => 'substitution#convert'

  # SEARCH PAGES
  get 'search' => redirect('/search/translations')
  get 'search/translations' => 'search#translations', as: :search_translations
  get 'search/keys' => 'search#keys', as: :search_keys
  get 'search/commits' => 'search#commits', as: :search_commits

  # STATS PAGES
  get 'stats' => 'stats#index'

  # GLOSSARY PAGES
  get 'glossary' => 'glossary#index', as: :glossary
  namespace 'glossary' do
    resources :sources, only: [:index, :create, :edit, :update, :destroy], controller: 'source_glossary_entries' do
      resources :locales, only: [:create, :edit, :update], controller: 'locale_glossary_entries' do
        member { patch :approve, :reject }
      end
    end
  end

  # HOME PAGES
  get 'administrators' => 'home#administrators', as: :administrators
  get 'translators' => 'home#translators', as: :translators
  get 'reviewers' => 'home#reviewers', as: :reviewers
  root to: 'home#index'

  require 'sidekiq/web'
  begin
    require 'sidekiq/pro/web'
  rescue LoadError
    # no sidekiq pro
  end
  constraint = lambda { |request| request.env['warden'].authenticate? and request.env['warden'].user.admin? }
  constraints(constraint) { mount Sidekiq::Web => '/sidekiq' }

  get '/queue_status' => proc {
    queue_size   = %w(high low).map { |q| Sidekiq::Queue.new(q).size }.inject(:+)
    queue_status = if queue_size == 0
                     'idle'
                   elsif queue_size < 21
                     'working'
                   else
                     'heavy'
                   end
    [200, {'Content-Type' => 'text/plain'}, [queue_status]]
  }
end

app/controllers/issues_controller.rb
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# Controller for working with {Issue Issues}.

class IssuesController < ApplicationController
  before_filter :find_project
  before_filter :find_key
  before_filter :find_translation
  before_filter :find_issue, only: [:update, :resolve, :subscribe, :unsubscribe]

  layout false
  respond_to :js

  # Creates an Issue for a Translation.
  #
  # Routes
  # ------
  #
  # * `POST /projects/:project_id/keys/:key_id/translations/:translation_id/issues`
  #
  # Path Parameters
  # ---------------
  #
  # |                  |                                                                    |
  # |:-----------------|:-------------------------------------------------------------------|
  # | `project_id`     | The slug of a Project.                                             |
  # | `key_id`         | The slug of a Key in that project.                                 |
  # | `translation_id` | The locale of a Translation relating to the above project and key. |
  #
  # Body Parameters
  # ---------------
  #
  # |         |                                         |
  # |:--------|:----------------------------------------|
  # | `issue` | Parameterized hash of Issue attributes. |

  def create
    issue = current_user.issues.create(issue_params.merge(translation: @translation))
    issues = @translation.issues.includes(:user, comments: :user).order_default
    render template: 'issues/create.js.erb', locals: {project: @project, key: @key, translation: @translation, issues: issues, issue: issue.errors.present? ? issue : Issue.new_with_defaults, created_issue: issue.errors.present? ? nil : issue }
  end

  # Updates an Issue for a Translation.
  #
  # Routes
  # ------
  #
  # * `PATCH /projects/:project_id/keys/:key_id/translations/:translation_id/issues/:id`
  #
  # Path Parameters
  # ---------------
  #
  # |                  |                                                                    |
  # |:-----------------|:-------------------------------------------------------------------|
  # | `project_id`     | The slug of a Project.                                             |
  # | `key_id`         | The slug of a Key in that project.                                 |
  # | `translation_id` | The locale of a Translation relating to the above project and key. |
  # | `id`             | The id of an Issue.                                                |
  #
  # Body Parameters
  # ---------------
  #
  # |         |                                         |
  # |:--------|:----------------------------------------|
  # | `issue` | Parameterized hash of Issue attributes. |

  def update
    @issue.update(issue_params)
    render 'issues/update.js.erb', locals: {project: @project, key: @key, translation: @translation, issue: @issue }
  end

  # Resolves an Issue by updating its status field.
  #
  # Routes
  # ------
  #
  # * `PATCH /projects/:project_id/keys/:key_id/translations/:translation_id/issues/:id/resolve`
  #
  # Path Parameters
  # ---------------
  #
  # |                  |                                                                    |
  # |:-----------------|:-------------------------------------------------------------------|
  # | `project_id`     | The slug of a Project.                                             |
  # | `key_id`         | The slug of a Key in that project.                                 |
  # | `translation_id` | The locale of a Translation relating to the above project and key. |
  # | `id`             | The id of an Issue.                                                |

  def resolve
    @issue.resolve(current_user)
    render 'issues/update.js.erb', locals: {project: @project, key: @key, translation: @translation, issue: @issue }
  end

  # Subscribes the current user to the Issue.
  #
  # Routes
  # ------
  #
  # * `PATCH /projects/:project_id/keys/:key_id/translations/:translation_id/issues/:id/subscribe`
  #
  # Path Parameters
  # ---------------
  #
  # |                  |                                                                    |
  # |:-----------------|:-------------------------------------------------------------------|
  # | `project_id`     | The slug of a Project.                                             |
  # | `key_id`         | The slug of a Key in that project.                                 |
  # | `translation_id` | The locale of a Translation relating to the above project and key. |
  # | `id`             | The id of an Issue.                                                |

  def subscribe
    @issue.skip_email_notifications = true
    @issue.subscribe(current_user)
    render 'issues/update.js.erb', locals: {project: @project, key: @key, translation: @translation, issue: @issue }
  end

  # Unsubscribes the current user to the Issue.
  #
  # Routes
  # ------
  #
  # * `PATCH /projects/:project_id/keys/:key_id/translations/:translation_id/issues/:id/unsubscribe`
  #
  # Path Parameters
  # ---------------
  #
  # |                  |                                                                    |
  # |:-----------------|:-------------------------------------------------------------------|
  # | `project_id`     | The slug of a Project.                                             |
  # | `key_id`         | The slug of a Key in that project.                                 |
  # | `translation_id` | The locale of a Translation relating to the above project and key. |
  # | `id`             | The id of an Issue.                                                |

  def unsubscribe
    @issue.skip_email_notifications = true
    @issue.unsubscribe(current_user)
    render 'issues/update.js.erb', locals: {project: @project, key: @key, translation: @translation, issue: @issue }
  end

  private

  def find_project
    @project = Project.find_from_slug!(params[:project_id])
  end

  def find_key
    @key = @project.keys.find_by_id!(params[:key_id])
  end

  def find_translation
    @translation = @key.translations.where(rfc5646_locale: params[:translation_id]).first!
  end

  def find_issue
    @issue = @translation.issues.includes(comments: :user).find_by_id!(params[:id])
  end

  def issue_params
    params.require(:issue).permit(:summary, :priority, :kind, :description, :status, :subscribed_emails).merge(updater_id: current_user.id)
  end
end

app/helpers/issues_helper.rb
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# Helper methods that are related to Issues.

module IssuesHelper

  # The url to view an issue.
  # Issue can be viewed in both an edit translation page and show translation page.
  # If `user` is provided, and is a translator, this will produce the issue url within
  # the edit translation page.
  #
  # @param [Issue] issue The issue of interest.
  # @param [User] user The user who will see this url.
  # @return [String] Url of the issue in the project_key_translation page, with the section identifier.

  def issue_url(issue, user=nil)
    raise ArgumentError, "Issue must be provided" unless issue.is_a?(Issue)

    args = [issue.translation.key.project, issue.translation.key, issue.translation, anchor: "issue-wrapper-#{issue.id}"]
    (user.try(:translator?) ? edit_project_key_translation_url(*args) : project_key_translation_url(*args))
  end
end

app/views/issues/_edit.html.slim
/ Copyright 2014 Square Inc.
/
/    Licensed under the Apache License, Version 2.0 (the "License");
/    you may not use this file except in compliance with the License.
/    You may obtain a copy of the License at
/
/        http://www.apache.org/licenses/LICENSE-2.0
/
/    Unless required by applicable law or agreed to in writing, software
/    distributed under the License is distributed on an "AS IS" BASIS,
/    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/    See the License for the specific language governing permissions and
/    limitations under the License.

= render partial: 'issues/form', locals: { project: project, key: key, translation: translation, issue: issue }

app/views/issues/_form.html.slim
/ Copyright 2014 Square Inc.
/
/    Licensed under the Apache License, Version 2.0 (the "License");
/    you may not use this file except in compliance with the License.
/    You may obtain a copy of the License at
/
/        http://www.apache.org/licenses/LICENSE-2.0
/
/    Unless required by applicable law or agreed to in writing, software
/    distributed under the License is distributed on an "AS IS" BASIS,
/    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/    See the License for the specific language governing permissions and
/    limitations under the License.

= form_for [project, key, translation, issue], remote: true, html: {class: 'issue-form'} do |f|
  - if issue.errors.any?
    .control-group.errors
      label.control-label Errors:
      .controls
        ul
          - issue.errors.full_messages.each do |msg|
            li = msg
  .control-group
    = f.label :type, class: 'control-label'
    .controls
      = f.select :kind, t('models.issue.kind').to_a.map(&:reverse)
  .control-group
    = f.label :priority, class: 'control-label'
    .controls
      = f.select :priority, t('models.issue.priority').to_a.map(&:reverse).tap{|outer_arr| outer_arr.each {|arr| arr[1] = nil if arr[1] == :none}}
  .control-group
    = f.label :summary, class: 'control-label'
    .controls
      = f.text_field :summary
  .control-group
    = f.label :description, class: 'control-label'
    .controls
      = f.text_area :description
  .control-group
    = f.label :subscribed_emails, class: 'control-label'
    .controls
      - emails = issue.errors.any? ? issue.subscribed_emails : (issue.subscribed_emails + [current_user.email]).uniq
      = f.text_field :subscribed_emails, value: emails.join(", "), placeholder: "person1@example.com, person2@example.com", class: "issue-subscribed-emails"
  - unless issue.new_record?
    .control-group
      = f.label :status, class: 'control-label'
      .controls
        = f.select :status, t('models.issue.status').to_a.map(&:reverse)
  .control-group
    .controls
      = f.submit
      = button_tag 'Cancel', class: "small default cancel-button"

app/views/issues/_index.html.slim
/ Copyright 2014 Square Inc.
/
/    Licensed under the Apache License, Version 2.0 (the "License");
/    you may not use this file except in compliance with the License.
/    You may obtain a copy of the License at
/
/        http://www.apache.org/licenses/LICENSE-2.0
/
/    Unless required by applicable law or agreed to in writing, software
/    distributed under the License is distributed on an "AS IS" BASIS,
/    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/    See the License for the specific language governing permissions and
/    limitations under the License.


/ Requires local_assigns to include project, key, translation, issues.
/ local_assigns[:issue] is optional. If provided, it will be assumed that the issue's creation failed.

.entry.row#issues data-search-url=search_users_url data-auto-fill=current_user.can_search_users?.to_s
  .sixteen.columns
    legend ISSUES

    = button_tag 'Create a New Issue', class: "default show-form-button #{'hide' if issue.errors.any?}"
    div class="form-wrapper loading-overlayable #{'hide' if issue.errors.blank?}"
      = render partial: 'issues/new', locals: { project: project, key: key, translation: translation, issue: issue }

    - if issues.present?
      h3 Existing Issues
      table.table.issues-table
        - issues.each do |issue|
          tr
            td
              = render partial: 'issues/show_wrapper', locals: { project: project, key: key, translation: translation, issue: issue }

app/views/issues/_new.html.slim
/ Copyright 2014 Square Inc.
/
/    Licensed under the Apache License, Version 2.0 (the "License");
/    you may not use this file except in compliance with the License.
/    You may obtain a copy of the License at
/
/        http://www.apache.org/licenses/LICENSE-2.0
/
/    Unless required by applicable law or agreed to in writing, software
/    distributed under the License is distributed on an "AS IS" BASIS,
/    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/    See the License for the specific language governing permissions and
/    limitations under the License.

= render partial: 'issues/form', locals: { project: project, key: key, translation: translation, issue: issue }

app/views/issues/_notifications_on_translation_page_header.html.slim
div#issue-notifications-on-translations-page-header
  - if issues.any?(&:pending?)
    = link_to "There are pending issues in this translation!", "#issues", "data-scroll-to" => "#issues", class: "has-pending-issues"

app/views/issues/_show.html.slim
/ Copyright 2014 Square Inc.
/
/    Licensed under the Apache License, Version 2.0 (the "License");
/    you may not use this file except in compliance with the License.
/    You may obtain a copy of the License at
/
/        http://www.apache.org/licenses/LICENSE-2.0
/
/    Unless required by applicable law or agreed to in writing, software
/    distributed under the License is distributed on an "AS IS" BASIS,
/    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/    See the License for the specific language governing permissions and
/    limitations under the License.

.issue id="issue-#{issue.id}"
  .control-group
    label.control-label
      | Type
    .controls
      = t("models.issue.kind")[issue.kind_was]
  .control-group
    label.control-label
      | Priority
    .controls
      = t("models.issue.priority")[issue.priority_was ? issue.priority_was : :none]
  .control-group
    label.control-label
      | Summary
    .controls
      = issue.summary_was
  .control-group
    label.control-label
      | Description
    .controls
      = issue.description_was
  .control-group
    label.control-label
      | Subscribed Emails
    .controls
      = issue.subscribed_emails_was.join(", ")
  .control-group
    label.control-label
      | Reporter
    .controls
      = issue.user_name
  .control-group
    label.control-label
      | Reported on
    .controls
      = l issue.created_at, format: :full

app/views/issues/_show_wrapper.html.slim
/ Copyright 2014 Square Inc.
/
/    Licensed under the Apache License, Version 2.0 (the "License");
/    you may not use this file except in compliance with the License.
/    You may obtain a copy of the License at
/
/        http://www.apache.org/licenses/LICENSE-2.0
/
/    Unless required by applicable law or agreed to in writing, software
/    distributed under the License is distributed on an "AS IS" BASIS,
/    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/    See the License for the specific language governing permissions and
/    limitations under the License.

- issue_wrapper_id = "issue-wrapper-#{issue.id}"

.issue-wrapper id="#{issue_wrapper_id}"
  .top-bar
    strong.pull-right
      | Status:
      span class="issue-status issue-status-#{issue.status}"
        = t("models.issue.status")[issue.status]
    .info
      strong = issue.user_name
      |  reported this issue on #{l issue.created_at, format: :full}

  .loading-overlayable
    .row
      .twelve.columns
        .show-issue-wrapper class="#{'hide' if issue.errors.any?}"
          = render partial: 'issues/show', locals: { project: project, key: key, translation: translation, issue: issue }

        = button_tag 'Edit Issue', class: "small default show-form-button #{'hide' if issue.errors.any?}"
        .form-wrapper class="#{'hide' if issue.errors.blank?}"
          = render partial: 'issues/edit', locals: { project: project, key: key, translation: translation, issue: issue }

      .four.columns.right-side
        - if issue.subscribed?(current_user)
          = button_to "Unsubscribe", unsubscribe_project_key_translation_issue_path(project, key, translation, issue), method: :patch, remote: true, class: 'btn default'
        - else
          = button_to "Subscribe", subscribe_project_key_translation_issue_path(project, key, translation, issue), method: :patch, remote: true, class: 'btn'

        - unless issue.resolved?
          = button_to "Resolve", resolve_project_key_translation_issue_path(project, key, translation, issue), method: :patch, remote: true, class: 'btn approve'

    .issue-comments-wrapper
      = render partial: 'comments/index', locals: {issue: issue, comment: local_assigns[:comment] || Comment.new}

app/views/issues/create.js.erb
<%
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
%>

<% # Replace the entire issues html with updated html %>
$('#issues').replaceWith('<%=j render partial: 'index', locals: {project: project, key: key, translation: translation, issues: issues, issue: issue} %>');

<% # Trigger 'render' events on issue forms to selectize emails field %>
$('#issues .issue-form').trigger('render');

<% if created_issue %>
    $(window).scrollTo('#issue-wrapper-<%=created_issue.id%>', 500);
<% end %>

app/views/issues/update.js.erb
<%
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
%>

<% # Replace the issue html with updated html %>
$('#issues #issue-wrapper-<%= issue.id %>').replaceWith('<%=j render partial: 'issues/show_wrapper', locals: local_assigns %>');

<% # Trigger a 'render' event to selectize emails field %>
$('#issues #issue-wrapper-<%= issue.id %> .issue-form').trigger('render');