config/routes.rb
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

Shuttle::Application.routes.draw do
  # Redirect request with not matching hosts or protocol to a default url.
  # For example, `http://shuttle.server1.example.com` would redirect to `https://shuttle.example.com`
  # if the default url provided in the configs were `https://shuttle.example.com`.
  full_root_url = lambda { |opts| opts.fetch(:protocol, 'http') + '://' + opts.host + (opts.key?(:port) ? ':' + opts.port.to_s : '')}.call(Shuttle::Configuration.app.default_url_options)
  constraints(lambda { |req| !req.url.start_with?(full_root_url) }) do
    match '*glob' => redirect(full_root_url), via: [:get, :post, :put, :patch, :delete]
  end

  # AUTHENTICATION
  devise_for :users, controllers: {
      registrations: 'registrations'
  }

  # API
  namespace :api do
    namespace :v1 do
      resources :projects, only: [] do
        resources :articles, param: :name, only: [:index, :new, :create, :show, :edit, :update] do
          member do
            get :manifest, :issues
          end
        end
      end
    end
  end

  # IN-CONTEXT TRANSLATION
  constraints(key_id: /[^\s]+/) do
    get '/projects/:project_id/commits/:commit_id/keys/:key_id/translations/:id' => 'incontext/translations#show', as: :incontext_translation
    get '/projects/:project_id/commits/:commit_id/keys/:key_id/translations/:id/edit' => 'incontext/translations#edit', as: :edit_incontext_translation
  end

  # REST
  resources :projects do
    resources :commits, only: [:show, :create, :update, :destroy] do
      member do
        post :sync, :recalculate, :ping_stash
        get :manifest, :localize, :search, :tools, :gallery, :issues
      end

      resources :keys, only: [:index, :show], controller: 'commit/keys'
      resources :screenshots, only: [:create] do
        collection do
          post :request, to: :request_screenshots
        end
      end
    end

    resources :keys, only: [] do
      resources :translations, only: [:show, :new, :create, :edit, :update] do
        member do
          get :match, :fuzzy_match
        end
      end

      resources :translations, only: [] do
        resources :issues, only: [:create, :update] do
          member do
            patch :resolve
            patch :subscribe
            patch :unsubscribe
          end
        end
      end
    end

    member do
      post 'github-pull-request-builder' => 'projects#github_webhook'
      post 'stash-pull-request-builder' => 'projects#stash_webhook'
      get  'mass-copy-translations' => 'projects#setup_mass_copy_translations', as: :setup_mass_copy_translations
      post 'mass-copy-translations' => 'projects#mass_copy_translations', as: :mass_copy_translations
    end
  end

  resources :issues, only: [] do
    resources :comments, only: [:create]
  end

  resources :locales, only: :index do
    collection { get :countries }
    resources :projects, only: [:index, :show], controller: 'locale/projects' do
      resources :translations, controller: 'locale/translations', only: :index
    end
    resources :glossary_entries, only: [:index, :create, :update, :destroy]
  end

  resources :users, only: [:index, :show, :update, :destroy] do
    collection { get :search }
    member { post :become }
  end

  resources :locale_associations, except: :show

  get 'substitute' => 'substitution#convert'

  # SEARCH PAGES
  get 'search' => redirect('/search/translations')
  get 'search/translations' => 'search#translations', as: :search_translations
  get 'search/keys' => 'search#keys', as: :search_keys
  get 'search/commits' => 'search#commits', as: :search_commits

  # STATS PAGES
  get 'stats' => 'stats#index'

  # GLOSSARY PAGES
  get 'glossary' => 'glossary#index', as: :glossary
  namespace 'glossary' do
    resources :sources, only: [:index, :create, :edit, :update, :destroy], controller: 'source_glossary_entries' do
      resources :locales, only: [:create, :edit, :update], controller: 'locale_glossary_entries' do
        member { patch :approve, :reject }
      end
    end
  end

  # HOME PAGES
  get 'administrators' => 'home#administrators', as: :administrators
  get 'translators' => 'home#translators', as: :translators
  get 'reviewers' => 'home#reviewers', as: :reviewers
  root to: 'home#index'

  require 'sidekiq/web'
  begin
    require 'sidekiq/pro/web'
  rescue LoadError
    # no sidekiq pro
  end
  constraint = lambda { |request| request.env['warden'].authenticate? and request.env['warden'].user.admin? }
  constraints(constraint) { mount Sidekiq::Web => '/sidekiq' }

  get '/queue_status' => proc {
    queue_size   = %w(high low).map { |q| Sidekiq::Queue.new(q).size }.inject(:+)
    queue_status = if queue_size == 0
                     'idle'
                   elsif queue_size < 21
                     'working'
                   else
                     'heavy'
                   end
    [200, {'Content-Type' => 'text/plain'}, [queue_status]]
  }
end

app/controllers/locale/projects_controller.rb
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# Controller for working with {Project Projects} in the context of a specific
# locale.

class Locale::ProjectsController < ApplicationController

  before_filter :translator_required
  before_filter :locale_access_required
  before_filter :find_locale
  before_filter :find_project, only: :show

  respond_to :html, only: :show
  respond_to :json, only: :index

  # Returns a list of Projects whose required locales include `locale`.
  #
  # Routes
  # ------
  #
  # * `GET /locales/:locale_id/projects.json`
  #
  # Path Parameters
  # ---------------
  #
  # |             |                                 |
  # |:------------|:--------------------------------|
  # | `locale_id` | The RFC 5646 code for a locale. |

  def index
    respond_with(@projects = Project.scoped.to_a.select { |p| p.targeted_rfc5646_locales.include? @locale.rfc5646 }) do |format|
      format.json { render json: decorate(@projects).to_json }
    end
  end

  # Displays a web page where a translator can view and edit the translations
  # for a project in a `locale`.
  #
  # Routes
  # ------
  #
  # * `GET /locales/:locale_id/projects/:id
  #
  # Path Parameters
  # ---------------
  #
  # |             |                                 |
  # |:------------|:--------------------------------|
  # | `locale_id` | The RFC 5646 code for a locale. |
  # | `id`        | The slug of a {Project}.        |

  def show
    translations_form = LocaleProjectsShowForm.new(params)
    translations_finder = LocaleProjectsShowFinder.new(translations_form)
    @translations = translations_finder.find_translations
    @glossary_entries = LocaleGlossaryEntry.includes(:source_glossary_entry).joins(:source_glossary_entry)
        .where(
            source_glossary_entries: {source_rfc5646_locale: Shuttle::Configuration.locales.source_locale},
            rfc5646_locale:          @locale.rfc5646,
            approved:                true)
        .map(&:as_translation_json)
        .compact
    @presenter = LocaleProjectsShowPresenter.new(@project, translations_form)
    respond_with @project
  end

  private

  def find_locale
    @locale = Locale.from_rfc5646(params[:locale_id])
    unless @locale
      respond_to do |format|
        format.any { head :not_found }
      end
    end
  end

  def find_project
    @project = Project.find_from_slug!(params[:id])
  end

  def decorate(projects)
    projects.map do |project|
      project.as_json.merge(
          url:                       locale_project_url(@locale.rfc5646, project),
          pending_translation_count: project.pending_translations(@locale),
          pending_review_count:      project.pending_reviews(@locale)
      )
    end
  end

  def locale_access_required
    if current_user.has_access_to_locale?(params[:locale_id])
      true
    else
      respond_to do |format|
        format.html { redirect_to root_url, alert: t('controllers.locale.projects.locale_access_required') }
        format.any { head :forbidden }
      end
      false
    end
  end
end

app/views/projects/_form.js.coffee.erb
# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

$(document).ready () ->
  setupLocaleField = () ->
    $("#project_required_rfc5646_locales, #project_other_rfc5646_locales").arrayField(
      renderer: (container, name, value) ->
        text_field = $('<input/>').attr('type', 'text')
                                  .attr('name', name)
                                  .attr('placeholder', "Locale")
                                  .addClass('locale-field')
                                  .val(value)
        text_field.appendTo container
        new LocaleField(text_field)
        return text_field
    )

  setupKeyFields = () ->
    $('#project_key_locale_exclusions, #project_key_locale_inclusions').hashField(
      renderer: (container, key, value) ->

        key_field = $('<div/>').addClass('hashfield-key').appendTo(container)
        value_field = $('<div/>').addClass('hashfield-multi-value').appendTo(container)

        new LocaleField(
          $('<input/>').attr(
              type: 'text'
              rel: 'key'
              placeholder: 'Locale'
              name: key
            ).val(key)
            .addClass('locale-field').appendTo(key_field)
        )

        valueField = $('<div/>').attr({rel: 'value', 'data-value': JSON.stringify(value)}).addClass('array-field').appendTo(value_field);
        valueField.arrayField(
          renderer: (container, name, value) ->
            $('<input/>').attr(
              name: name
              type: 'text'
              placeholder: 'Key or Glob'
            ).val(value).appendTo(container)
        )
    )

  setupPathFields = () ->
    $('#project_skip_importer_paths, #project_only_importer_paths').hashField(
      renderer: (container, key, value) ->
        key_field = $('<div/>').addClass('hashfield-key').appendTo(container)
        value_field = $('<div/>').addClass('hashfield-multi-value').appendTo(container)

        select = $('<select/>').attr({rel: 'key'}).appendTo(key_field)
        <% Importer::Base.implementations.each do |importer| %>
        $('<option/>').text("<%= escape_javascript importer.human_name %>")
          .attr({value: "<%= escape_javascript importer.ident %>", selected: key == "<%= escape_javascript importer.ident %>" ? 'selected' : ''})
          .appendTo(select)
        <% end %>
        select.val(key);

        valueField = $('<div/>').attr(
            rel: 'value',
            'data-value': JSON.stringify(value)
          ).addClass('array-field')
          .appendTo(value_field)

        valueField.arrayField()
    )

  $('.flipswitch-checkbox').each (i) ->
    id = $(this).attr('id')
    checked_elt = $("##{id}-checked")
    unchecked_elt = $("##{id}-unchecked")

    if $(this).is(':checked')
      unchecked_elt.hide()
    else
      checked_elt.hide()

    $(this).on 'change', ->
      if $(this).is(':checked')
        unchecked_elt.fadeOut ->
          checked_elt.fadeIn()
      else
        checked_elt.fadeOut ->
          unchecked_elt.fadeIn()

  if (window.localesLoaded)
    setupLocaleField()
    setupKeyFields()
    setupPathFields()
  else 
    $(document).bind('locales_loaded', setupLocaleField)
    $(document).bind('locales_loaded', setupKeyFields)
    $(document).bind('locales_loaded', setupPathFields)

app/views/projects/_form.slim
/ Copyright 2014 Square Inc.
/
/    Licensed under the Apache License, Version 2.0 (the "License");
/    you may not use this file except in compliance with the License.
/    You may obtain a copy of the License at
/
/        http://www.apache.org/licenses/LICENSE-2.0
/
/    Unless required by applicable law or agreed to in writing, software
/    distributed under the License is distributed on an "AS IS" BASIS,
/    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/    See the License for the specific language governing permissions and
/    limitations under the License.

= form_for @project do |f|
  .row
    .eight.columns
      fieldset
        legend General Settings
        .control-group
          = f.label :name, class: 'control-label'
          .controls
            = f.text_field :name

        .control-group
          = f.label :repository_url, class: 'control-label'
          .controls
            = f.text_field :repository_url, class: 'tooltip-parent', :'data-tooltip' => '#repository_url_tooltip'
            .tooltip#repository_url_tooltip
              | This is the URL you use to check out the project in Git,
              strong not
              |  the GitHub website URL.

        .control-group
          = f.label :github_webhook_url, class: 'control-label'
          .controls
            = f.text_field :github_webhook_url, class: 'tooltip-parent', :'data-tooltip' => '#github_webhook_url_tooltip'
            .tooltip#github_webhook_url_tooltip
              | This URL will be posted to when a commit is marked as 'ready'. HTTP Post body will contain
              tt commit_revision
              | ,
              tt project_name
              |  and
              tt ready
              |  status.
        .control-group
          = f.label :stash_webhook_url, class: 'control-label'
          .controls
            = f.text_field :stash_webhook_url, class: 'tooltip-parent', :'data-tooltip' => '#stash_webhook_url_tooltip'
            .tooltip#stash_webhook_url_tooltip
              | This URL will be posted to when a commit's status is changed.
                It is used to update the build status of a commit and is primarily meant
                to integrate with Stash.  HTTP Post body will contain
              tt state
              | ,
              tt key
              | ,
              tt name
              | ,
              tt url
              |  and,
              tt description
              |  .
      fieldset
        legend Locale Settings
        .control-group
          = f.label :base_rfc5646_locale, class: 'control-label'
          .controls
            = f.text_field :base_rfc5646_locale, class: 'locale-field tooltip-parent',\
                                                 :'data-tooltip' => '#base_rfc5646_tooltip',\
                                                 disabled: !current_user.try!(:admin?)
            .tooltip#base_rfc5646_tooltip
              | The locale that the original copy is written in.

        .control-group
          = f.label :required_rfc5646_locales, 'Required Localizations', class: 'control-label'
          .controls
            - if current_user.try!(:admin?)
              = f.content_tag_field 'div', :required_rfc5646_locales, \
                class: 'array-field', 'data-value' => @project.required_rfc5646_locales.to_json
            - else
              - @project.required_rfc5646_locales.each do |locale|
                .spaced-field: input type="text" class='locale-field' value=locale disabled=true

        .control-group
          = f.label :other_rfc5646_locales, 'Other Localizations', class: 'control-label'
          .controls
            - if current_user.try!(:admin?)
              = f.content_tag_field 'div', :other_rfc5646_locales, \
                class: 'array-field', 'data-value' => @project.other_rfc5646_locales.to_json
            - else
              - @project.other_rfc5646_locales.each do |locale|
                .spaced-field: input type="text" class='locale-field' value=locale disabled=true

      fieldset
        legend Import Settings

        / Skip Imports
        .control-group
          = f.label :use_imports, "Use These Importers", class: 'control-label'
            / create a hidden field first so that if all checkboxes are unchecked, we at least get an empty array
          = hidden_field_tag 'project[use_imports][]', ''
          - Importer::Base.implementations.sort_by(&:human_name).each_with_index do |importer, index|
            .controls.checkboxes_and_radios
              = label_tag "project_use_imports_#{index}", class: 'checkbox'
                = importer.human_name
              = check_box_tag "project[use_imports][]", importer.ident, !@project.persisted? ? false : !@project.skip_imports.include?(importer.ident), id: "project_use_imports_#{index}"
          / p.help-block
          / | A comma-delimited list of locales to target. Include
          / - if PseudoTranslator.supported_rfc5646_locales.count > 1
          /   | any of
          / - PseudoTranslator.supported_rfc5646_locales.each do |l|
          /   code l
          / |  to generate pseudo-translations.
          /

        .control-group
          = f.label :watched_branches, class: 'control-label'
          .controls
            / = f.text_field :watched_branches
            / .list-field
            = f.content_tag_field 'div', :watched_branches, class: 'array-field', 'data-value' => @project.watched_branches.to_json
            p.help-block New commits that appear on any of these branches will be automatically imported.

        .control-group
          = f.label :touchdown_branch, class: 'control-label'
          .controls
            = f.text_field :touchdown_branch
            p.help-block
              | Any time a commit from the <strong>first</strong> watched branch
              |  finishes translation, the head of this branch will be advanced
              |  to that commit. See the developer guide for more information.

        .control-group
          = f.label :manifest_directory, class: 'control-label'
          .controls
            = f.text_field :manifest_directory
            p.help-block
              | If this directory is specified, Shuttle will automatically create
              | a new commit that contains your translated manifest in the specified
              | directory and push it to your touchdown branch.

        .control-group
          = f.label :manifest_filename, class: 'control-label'
          .controls
            = f.text_field :manifest_filename
            p.help-block
              | If the filename is specified, then Shuttle will create a
              | file using the given filename.  Otherwise, it will default to
              | manifest.[default_file_extension]
      fieldset
        legend Export Settings

        .control-group
          = f.label :default_manifest_format, class: 'control-label'
          .controls.checkboxes_and_radios
            = label_tag "project_default_manifest_format_none", 'None'
            = radio_button_tag 'project[default_manifest_format]', '', @project.default_manifest_format.blank?
          - Exporter::Base.implementations.select(&:multilingual?).sort_by(&:human_name).each_with_index do |importer, index|
            .controls.checkboxes_and_radios
              = f.label "default_manifest_format_#{index}", class: 'radio'
                = importer.human_name
              = f.radio_button :default_manifest_format, importer.request_format.to_s


    .eight.columns.right-side
      .flipswitch
        input#key-flipswitch.flipswitch-checkbox checked=@project.key_inclusions.empty? name="project[use_key_exclusions]" type="checkbox"
          label.flipswitch-label for="key-flipswitch"
            .flipswitch-inner
            .flipswitch-switch
      fieldset
        legend Key Filtering

        .space-group#key-flipswitch-unchecked
          = f.label :key_inclusions, class: 'control-label'
          p.help-block List the keys that must be translated. If at least one inclusion is given, keys not matching will not be translated. UNIX-style globs are supported.
          .controls
            = f.content_tag_field 'div', :key_inclusions, class: 'array-field', 'data-value' => @project.key_inclusions.to_json

        .space-group#key-flipswitch-checked
          = f.label :key_exclusions, class: 'control-label'
          p.help-block List the keys you do not want to be translated. UNIX-style globs are supported.
          .controls
            = f.content_tag_field 'div', :key_exclusions, class: 'array-field', 'data-value' => @project.key_exclusions.to_json

      fieldset
        legend Locale Key Filtering

        .space-group
          = f.label :key_locale_inclusions, class: 'control-label'
          p.help-block List the keys that must be translated. If at least one inclusion is given, keys not matching will not be translated. UNIX-style globs are supported.
          .controls
            = f.content_tag_field 'div', :key_locale_inclusions, class: 'hash-field', 'data-value' => @project.key_locale_inclusions.to_json


        .space-group
          = f.label :key_locale_exclusions, class: 'control-label'
          p.help-block List the keys you do not want to be translated. UNIX-style globs are supported.
          .controls
            = f.content_tag_field 'div', :key_locale_exclusions, class: 'hash-field', 'data-value' => @project.key_locale_exclusions.to_json


      .flipswitch
        input#path-flipswitch.flipswitch-checkbox checked=@project.only_paths.empty? name="project[use_skip_paths]" type="checkbox"
          label.flipswitch-label for="path-flipswitch"
            .flipswitch-inner
            .flipswitch-switch
      fieldset
        legend Path Filtering

        .space-group#path-flipswitch-unchecked
          = f.label :only_paths, class: 'control-label'
          p.help-block List paths that importers will search for strings. Paths not in this list will not be searched.
          .controls
            = f.content_tag_field 'div', :only_paths, class: 'array-field', 'data-value' => @project.only_paths.to_json


        .space-group#path-flipswitch-checked
          = f.label :skip_paths, class: 'control-label'
          p.help-block List paths you do not want any importers to scan under for strings.
          .controls
            = f.content_tag_field 'div', :skip_paths, class: 'array-field', 'data-value' => @project.skip_paths.to_json

      fieldset
        legend Importer Path Filtering

        .space-group
          = f.label :only_importer_paths, class: 'control-label'
          p.help-block List paths for specific importers to search on. Paths not in this list will not be searched by that importer.
          .controls
            = f.content_tag_field 'div', :only_importer_paths, class: 'hash-field', 'data-value' => @project.only_importer_paths.to_json


        .space-group
          = f.label :skip_importer_paths, class: 'control-label'
          p.help-block List paths that you want specific importers to skip.
          .controls
            = f.content_tag_field 'div', :skip_importer_paths, class: 'hash-field', 'data-value' => @project.skip_importer_paths.to_json



  - if current_user.admin? && @project.persisted?
    .header.advanced_actions_header
      h1 Advanced
    hr.divider

    .row
      .eight.columns
        fieldset
          legend Multi Locale Translations

          .space-group
            = f.label :disable_locale_association_checkbox_settings, class: 'control-label'
            .controls
              = f.check_box :disable_locale_association_checkbox_settings

          .space-group
            = link_to "Mass Copy Translations From One Locale Into Another", setup_mass_copy_translations_project_url

    - unless @project.git?
      .row
        .eight.columns
          fieldset
            legend Article API Token

            .space-group
              .controls
                code
                  = @project.api_token

  .form-actions
    = f.submit class: 'primary', value: 'save', data: { confirm: 'Are you sure?  Changes are irreversible.'}
    button.default href=projects_url Cancel

- content_for :javascript do
  script type='text/javascript'
    - file_name = 'views/projects/_form'
    - js_coffee_erb_file  = Rails.root.join('app', file_name + '.js.coffee.erb')
    = raw(CoffeeScript.compile(ERB.new(File.read(js_coffee_erb_file)).result(binding))) if File.exist?(js_coffee_erb_file)

app/views/projects/edit.slim
/ Copyright 2014 Square Inc.
/
/    Licensed under the Apache License, Version 2.0 (the "License");
/    you may not use this file except in compliance with the License.
/    You may obtain a copy of the License at
/
/        http://www.apache.org/licenses/LICENSE-2.0
/
/    Unless required by applicable law or agreed to in writing, software
/    distributed under the License is distributed on an "AS IS" BASIS,
/    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/    See the License for the specific language governing permissions and
/    limitations under the License.
- content_for :shuttle_title do
  = "#{@project.name} Settings - Shuttle"
- content_for :file_name do
  = 'views/projects/edit'

.header
  h1 Edit settings for #{@project.name}
hr.divider

= render partial: 'projects/form' 

app/views/projects/index.slim
/ Copyright 2014 Square Inc.
/
/    Licensed under the Apache License, Version 2.0 (the "License");
/    you may not use this file except in compliance with the License.
/    You may obtain a copy of the License at
/
/        http://www.apache.org/licenses/LICENSE-2.0
/
/    Unless required by applicable law or agreed to in writing, software
/    distributed under the License is distributed on an "AS IS" BASIS,
/    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/    See the License for the specific language governing permissions and
/    limitations under the License.
- content_for :shuttle_title do
  = "Projects - Shuttle"
- content_for :file_name do
  = 'views/projects/index'

.header
  .pull-right
    button.primary href=new_project_url Add Project
  h1 Projects

hr.divider

.border
  table.table.hover-rows
    thead
      tr
        th Project
        th Repository URL
        th Required Locales
        th Optional Locales
    tbody
      - @projects.each do |project|
        tr onclick="document.location = '#{edit_project_url(project)}'"
          td = project.name
          td = project.repository_url
          td = project.required_rfc5646_locales.join(" / ").upcase
          td = project.other_rfc5646_locales.join(" / ").upcase

app/views/projects/new.slim
/ Copyright 2014 Square Inc.
/
/    Licensed under the Apache License, Version 2.0 (the "License");
/    you may not use this file except in compliance with the License.
/    You may obtain a copy of the License at
/
/        http://www.apache.org/licenses/LICENSE-2.0
/
/    Unless required by applicable law or agreed to in writing, software
/    distributed under the License is distributed on an "AS IS" BASIS,
/    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/    See the License for the specific language governing permissions and
/    limitations under the License.
- content_for :shuttle_title do
  = "New Project - Shuttle"
- content_for :file_name do
  = 'views/projects/new'

.header
  h1 Add Project

hr.divider

= render partial: 'projects/form' 

app/views/projects/setup_mass_copy_translations.slim
/ Copyright 2014 Square Inc.
/
/    Licensed under the Apache License, Version 2.0 (the "License");
/    you may not use this file except in compliance with the License.
/    You may obtain a copy of the License at
/
/        http://www.apache.org/licenses/LICENSE-2.0
/
/    Unless required by applicable law or agreed to in writing, software
/    distributed under the License is distributed on an "AS IS" BASIS,
/    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/    See the License for the specific language governing permissions and
/    limitations under the License.
- content_for :shuttle_title do
  = "Mass Copy Translations"
- content_for :file_name do
  = 'views/projects/mass_copy_translations'

.header
  h1
    | Mass Copy Translations for #{@project.name}

hr.divider

legend Important ReadMe
p Please make sure that you understand what this tool will do, by reading all of this readme.
br

ul
  li
    | This project's base locale is
    strong
      |  "#{@project.base_rfc5646_locale}".
  li
    | This project's targeted locales are
    strong
      |  #{@project.targeted_rfc5646_locales.keys}.
    =< link_to 'Update your locales.', edit_project_url(@project)
  li This tool will copy all approved translations from 'from' locale into not-translated 'to' locale.
  li It will not override already existing translations in the target locale. If the string is already translated in the target locale, it will not be updated.
  li You can only copy between the locales which are in the same language family (same iso639), and in your targeted locales.
  li This tool will not create the translation records. The translation records should exist in the database beforehand.
  li This is not an instantaneous task. This task will run in the background for a while. Check Sidekiq for progress.
br

= form_tag mass_copy_translations_project_url(@project) do
  fieldset
    legend Ready To Party?

    .control-group
      = label_tag 'From (Source):', nil, class: 'control-label'
      .controls
        = text_field_tag :from_rfc5646_locale, params[:from_rfc5646_locale], class: 'locale-field'
    .control-group
      = label_tag 'To (Target):', nil, class: 'control-label'
      .controls
        = text_field_tag :to_rfc5646_locale, params[:to_rfc5646_locale], class: 'locale-field'

    .form-actions
      = submit_tag 'Mass Copy Translations', class: 'danger', data: { confirm: 'Are you sure? Did you carefully read the consequences of continuing. Changes are irreversible.'}
      = link_to 'Cancel', edit_project_url(@project), class: 'button default'